name: level2
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - numpy
  - pandas
  - h5py
  - gffutils
  - pysam
  - edlib
  - biopython
  - typer
  - tqdm
  - rich
  - pip
  - pip:
      - openspliceai==0.0.4
